//============================================================================================================
//
//
//                  Copyright (c) 2024-2025 Qualcomm Innovation Center, Inc. All rights reserved.
//                              SPDX-License-Identifier: BSD-3-Clause
//
//============================================================================================================

#include "sgsr_common.ush"
#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/ThirdParty/SGSR/3PassCS/sgsr_convert.hlsl"
